export const RecipeData = [
  {
    id: "1",
    title: "Dana Eti ile Dilimlenmiş Domates",
    description: "Kiev, Ukrayna'nın geleneksel tarifi olan yoğurtlu ve salatalı patlıcan dolması",
    imgUrl: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cmVjaXBlfGVufDB8fDB8fHww",
    malzemeler: [
      "1 adet taze tarak",
      "Yarım su bardağı zeytinyağı",
      "1 adet limon suyu",
      "2 diş sarımsak",
      "Yarım çay bardağı ince kıyılmış taze soğan",
      "Tuz ve karabiber",
    ],
    yapilis: [
      "Dana etini isteğinize göre dilimleyin. İsteğe bağlı olarak eti marine etmek için biraz zeytinyağı, tuz ve karabiberle karıştırabilirsiniz.",
      "Bir tavada ya da ızgarada eti pişirin. Pişirme süresi etin kalınlığına ve tercihinize bağlı olarak değişebilir. Etlerin her iki tarafını da güzelce kızartın.",
      "Domatesleri dilimleyin ve servis tabağına yerleştirin.",
      "Pişmiş dana etini dilimleyerek domateslerin üzerine yerleştirin.",
      "Zeytinyağı, limon suyu, ince kıyılmış taze soğan, ve isteğe bağlı olarak sarımsakları karıştırarak sos hazırlayın.",
      "Hazırladığınız sosu et ve domateslerin üzerine gezdirin.",
      "Tuz ve karabiber ekleyerek servis yapın.", 
    ],
  },

  {
    id: "2",
    title: "Dilimlenmiş Avokado",
    description: "Dilimlenmiş avokado, domates ve taze sebzelerle kızartılmış sığır eti salatası. İnce dilimlenmiş sashimi stili.",
    imgUrl: "https://images.unsplash.com/photo-1696824818313-1a1563281d22?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    malzemeler: [
      "2 adet olgun avokado",
      "1 adet büyük boy domates",
      "1/2 adet kırmızı soğan",
      "1/4 su bardağı doğranmış taze kişniş (isteğe bağlı)",
      "1 adet lime veya limon suyu",
      "Tuz ve karabiber (isteğe bağlı)",
    ],
    yapilis: [    
      "Olgun avokadoları ikiye bölün ve çekirdekleri çıkarın.",
      "Bir kaşık yardımıyla avokado etlerini bir kaba alın.",
      "Domatesi küçük küçük doğrayın ve avokadoya ekleyin.",
      "Kırmızı soğanı ince bir şekilde doğrayın ve karışıma ekleyin.",
      "Taze kişnişi doğrayıp ekleyebilirsiniz.",
      "Lime veya limon suyunu sıkarak karışıma ekleyin.",
      "Tuz ve karabiber ekleyerek karışımı dikkatlice karıştırın.",
      "Karışımı buzdolabında bir süre dinlendirerek servis yapabilirsiniz.",
    ],
  },

  {
    id: "3",
    title: "Steak Dinner",
    description: "Steak Dinner, genellikle özel günlerde veya özel davetlerde tercih edilen bir yemek seçeneğidir.",
    imgUrl: "https://images.unsplash.com/photo-1485704686097-ed47f7263ca4?q=80&w=3292&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  malzemeler: [
    "Steak (isteğe bağlı olarak tercih ettiğiniz kesim)",
    "Tuz",
    "Karabiber",
    "Zeytinyağı",
    "Teriyaki sosu (isteğe bağlı)",
    "Rosemary (isteğe bağlı)",
  ],
  yapilis: [
    "Steak'i oda sıcaklığına gelmesi için bir süre bekletin.",
    "Steak'in her iki tarafına tuz ve karabiber serpip ovalayın.",
    "Bir tavada veya ızgarada orta-yüksek ateşte, tercihinize göre pişirme derecesine gelene kadar steak'i pişirin.",
    "Pişirme sırasında, her iki tarafına da zeytinyağı sürün veya teriyaki sosu ile marine edebilirsiniz.",
    "Steak piştikten sonra, birkaç dakika dinlendirin.",
    "Dilimleyerek servis tabağına alın.",
    "Üzerine isteğe bağlı olarak taze rosemary yaprakları serperek servis yapın.",
  ],
},

  {
    id: "4",
    title: "Kremalı Hindistan Cevizi Körisi",
    description: "Her kaşıkta sizi Tayland'ın hareketli sokaklarına taşıyacak sıcak ve tatmin edici bir yemek.",
    imgUrl: "https://images.unsplash.com/photo-1680991554256-da64cc827619?q=80&w=3431&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  malzemeler: [
    "1 su bardağı kırmızı mercimek",
    "1 su bardağı yeşil mercimek",
    "1 su bardağı kuru nohut",
    "1 su bardağı hindistancevizi sütü",
    "1 adet soğan",
    "2 diş sarımsak",
    "1 yemek kaşığı taze zencefil",
    "1 yemek kaşığı hindistancevizi yağı",
    "1 yemek kaşığı köri tozu",
    "1 tatlı kaşığı toz zerdeçal",
    "1 tatlı kaşığı kimyon",
    "Tuz ve karabiber",
    "Taze kişniş veya maydanoz",
  ],
  yapilis: [
    "Kırmızı mercimek, yeşil mercimek ve haşlanmış nohutu iyice yıkayın ve süzün.",
    "Bir tencerede hindistancevizi yağını ısıtın. Rendelenmiş soğanı, ezilmiş sarımsağı ve rendelenmiş zencefili ekleyip kısık ateşte yumuşayana kadar soteleyin.",
    "Baharatları ekleyip karıştırın.",
    "Yıkanmış mercimek ve haşlanmış nohutu tencereye ekleyin, karıştırın.",
    "Hindistancevizi sütünü ekleyip karıştırın. Tuz ve karabiber ekleyerek damak zevkinize göre tatlandırın.",
    "Köri kısık ateşte mercimekler iyice pişene ve köri sosu koyu bir kıvama gelene kadar pişirin.",
  ],
},

  {
    id: "5",
    title: "Körili Karides",
    description: "Körili karides, lezzetli bir deniz ürünü olan karidesin baharatlı ve aromatik bir karışımla pişirilmiş hali olarak tanımlanabilir.",
    imgUrl: "https://images.unsplash.com/photo-1528502499757-107ea9369104?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",

  malzemeler: [
    "500 gram karides (temizlenmiş ve soyulmuş)",
    "2 yemek kaşığı sıvı yağ",
    "1 adet soğan",
    "2 diş sarımsak",
    "1 yemek kaşığı rendelenmiş taze zencefil",
    "1 yemek kaşığı köri tozu",
    "1 çay kaşığı toz kırmızı biber",
    "1 adet limon suyu",
    "Tuz ve karabiber",
    "Taze kişniş veya maydanoz (servis için)",
  ],
  yapilis: [
    "Karidesleri temizleyin ve kabuklarını soyun.",
    "Geniş bir tavada sıvı yağı ısıtın. Doğranmış soğanı ekleyip pembeleşene kadar kavurun.",
    "Ezilmiş sarımsak ve rendelenmiş taze zencefili ekleyip kokusu çıkana kadar soteleyin.",
    "Temizlenmiş karidesleri tavaya ekleyin ve karidesler pembeleşene kadar kısık ateşte pişirin.",
    "Köri tozunu ekleyip karideslere karıştırın. İsteğe bağlı olarak toz kırmızı biberi de ekleyebilirsiniz.",
    "Karidesler piştikten sonra taze kişniş veya maydanoz ile süsleyerek sıcak servis yapın.",
  ],
},

 {
   id: "6",
   title: "Tavuk Rulosu",
   description: "Tavuk rulosu, tavuk göğsü veya tavuk but eti kullanılarak hazırlanan, iç harcında çeşitli malzemelerin bulunduğu bir yemektir.",
   imgUrl: "https://images.unsplash.com/photo-1517609948086-6a03114ae1af?q=80&w=2972&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
 malzemeler: [
  "4 adet tavuk göğsü",
  "200 gram ıspanak",
  "1 su bardağı rendelenmiş kaşar peyniri",
  "1 çay bardağı zeytinyağı",
  "2 diş sarımsak",
  "1 tatlı kaşığı pul biber (isteğe bağlı)",
  "1 adet limon suyu",
  "Kürdan veya şiş",
 ],
 yapilis: [
  "Tavuk göğüslerini ince dilimler halinde kesin ve bir et dövme aparatı veya merdane yardımıyla daha da inceltin.",
  "İncelenmiş tavuk dilimlerini tezgaha serin.",
  "Üzerine doğranmış ıspanakları, rendelenmiş kaşar peynirini, ezilmiş sarımsağı serpiştirin.",
  "Tuz, karabiber, pul biber ve limon suyu ekleyerek malzemeleri tavuk dilimlerinin üzerine yayın.",
  "Tavuk dilimlerini rulo şeklinde sarın. Ruloları tutturmak için kürdan veya şiş kullanabilirsiniz.",
  "Tavuk rulolarını önceden ısıtılmış ızgarada veya tavada her iki tarafını da güzelce kızartın.",
 ],
},

 {
   id: "7",
   title: "Sonbahar Çorbası",
   description: "Sonbahar çorbası, mevsimine uygun olarak çeşitli sebzelerin ve baharatların kullanıldığı, sıcak ve besleyici bir çorba türüdür.",
   imgUrl: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
   malzemeler: [
    "2 su bardağı balkabağı",
    "2 adet havuç",
    "1 adet soğan",
    "2 diş sarımsak",
    "1 su bardağı kırmızı mercimek",
    "1 tatlı kaşığı toz zerdeçal",
    "1 yemek kaşığı tereyağı veya zeytinyağı",
    "6 su bardağı sebze veya tavuk suyu",
    "1 su bardağı süt",
    "Taze kişniş veya maydanoz",
   ],
   yapilis: [
    "Büyük bir tencerede tereyağı veya zeytinyağını ısıtın.",
    "Doğranmış soğanı ekleyip yumuşayana kadar kavurun.",
    "Rendelenmiş balkabağı, doğranmış havuç, sarımsak ve yıkanmış kırmızı mercimeği tencereye ekleyin.",
    "Sebzeleri birkaç dakika karıştırarak kavurun.",
    "Sebze veya tavuk suyunu ekleyin, karışım kaynayana kadar yüksek ateşte pişirin.",
    "Kaynadıktan sonra ateşi kısın ve sebzeler iyice yumuşayana kadar pişirin.",
    "Çorbayı blender veya çubuk blender ile pürüzsüz hale getirin.",
    "İsteğe bağlı olarak sütü ekleyip karıştırın.",
   ],
 },

 {
   id: "8",
   title: "Vegan Sushi",
   description: "Vegan sushi, geleneksel sushi tariflerinde kullanılan balık yerine vegan malzemelerin kullanıldığı, bitkisel bazlı bir sushi çeşididir.",
   imgUrl: "https://images.unsplash.com/photo-1703080173985-936514c7c8bd?q=80&w=3435&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
 malzemeler: [
  "2 su bardağı sushi pirinci ",
  "2,5 su bardağı su ",
  "1/2 su bardağı pirinç sirkesi ",
  "2 yemek kaşığı şeker ",
  "1 tatlı kaşığı tuz ",
  "Nori yosunu yaprakları ",
  "Yarım salatalık ",
  "1 havuç ",
  "1 avokado  ",
  "Soya sosu ",
 ],
 yapilis: [
  "Sushi pirincini iyice yıkayın ve 2,5 su bardağı su ile birlikte bir tencereye koyun.",
  "Pirinç suyunu çekene kadar yüksek ateşte kaynatın, ardından kısık ateşte pirinç suyunu çekene kadar pişirin.",
  "Pirinci bir kaba alın, pirinç sirkesini, şekeri ve tuzu ekleyip karıştırın.",
  "Nori yosunu yapraklarını sushi makisu (makis matı) üzerine yerleştirin.",
  "Elleriniz ıslakken pirinci nori yaprağına eşit şekilde yayın, kenarlarına bir boşluk bırakın.",
  "Uzunlamasına doğranmış salatalık, havuç ve avokado şeritlerini pirincin üzerine yerleştirin.",
  "Sushi matını kullanarak nori yosunu ile birlikte malzemeleri rulo şeklinde sarın.",
  "Rulo şeklindeki sushiyi bıçak yardımıyla dilimlere ayırın.",
 ],
},
];